import type { GameDef, PromptCard, AnswerCard } from "./types";

function prompts(arr: Array<string | [string, number]>): PromptCard[] {
  return arr.map((item, i) => {
    if (Array.isArray(item)) {
      return { id: `p${i}`, text: item[0], pick: item[1] };
    }
    return { id: `p${i}`, text: item };
  });
}

function answers(arr: string[]): AnswerCard[] {
  return arr.map((text, i) => ({ id: `a${i}`, text }));
}

/* ────────────────────────────────────────────────────────────────────────── */
/* 1. FILL IN THE BLANK — a Cards Against Humanity-style absurd party game.     */
/* ────────────────────────────────────────────────────────────────────────── */
const fillBlank: GameDef = {
  id: "fill-blank",
  name: "Fill In The Blank",
  emoji: "🃏",
  tagline: "Complete the sentence. Regret nothing.",
  accent: "#f5c518",
  promptLabel: "The prompt",
  answerLabel: "Your hand",
  prompts: prompts([
    "My therapist says my biggest red flag is ___.",
    "The secret ingredient in grandma's famous recipe is ___.",
    "I got fired for bringing ___ to the company picnic.",
    "Nothing ruins a first date faster than ___.",
    "The new Olympic sport that nobody asked for: ___.",
    "What's keeping me up at 3 a.m.? ___.",
    "The motivational poster in hell just says ___.",
    "I'd be a millionaire if I had a dollar for every ___.",
    "Welcome to my TED Talk on ___.",
    "The real reason the dinosaurs went extinct: ___.",
    ["My autobiography is titled ___, and the sequel is ___.", 2],
    "Studies show that 9 out of 10 doctors recommend ___.",
    "The group chat went silent after someone sent ___.",
    "My spirit animal is just ___ in a tiny hat.",
    "The worst possible thing to whisper during a hug: ___.",
    "Customer service can't help you with ___.",
    "I knew the wedding was doomed when I saw ___.",
    "Step one of my morning routine is ___.",
    ["A balanced breakfast includes ___ and a healthy serving of ___.", 2],
    "The haunted house was scary until we found ___ in the basement.",
    "My final words will probably be about ___.",
    "The app store rejected my app because of ___.",
  ]),
  answers: answers([
    "aggressively making eye contact",
    "a single, perfect chicken nugget",
    "emotional support raccoons",
    "explaining the plot of Inception, uninvited",
    "a suspiciously confident toddler",
    "my browser history",
    "screaming into a decorative pillow",
    "the audacity",
    "a PowerPoint with 94 slides",
    "running away from my responsibilities",
    "an unpaid internship",
    "haunted Tupperware",
    "the slow descent into madness",
    "interpretive dance",
    "a goose with a vendetta",
    "passive-aggressive sticky notes",
    "crying in the cereal aisle",
    "a motivational speaker nobody hired",
    "questionable life choices",
    "a raccoon wearing a tuxedo",
    "existential dread, but make it fashion",
    "gluten",
    "a Roomba seeking revenge",
    "my unread emails",
    "selling feet pics to the mafia",
    "a lukewarm cup of disappointment",
    "the ghost of my New Year's resolutions",
    "an inflatable T-Rex costume",
    "way too much confidence and zero plan",
    "a clown with a law degree",
    "spontaneous combustion",
    "my one (1) personality trait",
    "a deeply cursed Roomba",
    "the void, but it has wifi",
    "a pigeon that knows what it did",
    "tax fraud, allegedly",
  ]),
};

/* ────────────────────────────────────────────────────────────────────────── */
/* 2. HORRIBLE THERAPIST — give the worst possible advice to real problems.    */
/* ────────────────────────────────────────────────────────────────────────── */
const horribleTherapist: GameDef = {
  id: "horrible-therapist",
  name: "Horrible Therapist",
  emoji: "🛋️",
  tagline: "A patient needs help. Give them the worst advice imaginable.",
  accent: "#7c5cff",
  promptLabel: "The patient says",
  answerLabel: "Your professional advice",
  prompts: prompts([
    "\"I think my roommate is stealing my food.\" Doctor, what should I do?",
    "\"I'm terrified of public speaking.\" How do I get over it?",
    "\"My partner says I never listen.\" How can I improve?",
    "\"I keep procrastinating on everything.\" Help me fix this.",
    "\"I'm having trouble sleeping at night.\" Any advice?",
    "\"My boss takes credit for all my work.\" What do I do?",
    "\"I get anxious in large crowds.\" How should I cope?",
    "\"I can't stop comparing myself to others.\" What now?",
    "\"My kids won't stop fighting.\" Doctor, please.",
    "\"I'm scared of commitment.\" How do I move forward?",
    "\"I have a big presentation tomorrow.\" Calm me down.",
    "\"I think I'm burnt out at work.\" What's the cure?",
    "\"My neighbor plays loud music at 2 a.m.\" Help.",
    "\"I feel like nobody understands me.\" What should I try?",
    "\"I'm nervous about meeting my in-laws.\" Tips?",
    "\"I keep having the same nightmare.\" What does it mean?",
    "\"I spent my whole paycheck already.\" How do I budget?",
    "\"I'm afraid of growing old.\" How do I make peace with it?",
    "\"My friend never texts back.\" Should I be worried?",
    "\"I can't focus when I work from home.\" Suggestions?",
  ]),
  answers: answers([
    "have you tried screaming about it instead",
    "simply become the villain",
    "respond exclusively in interpretive dance",
    "move to the woods and adopt a crow",
    "set everything you own on fire (metaphorically)(or not)",
    "manifest it harder, you're just not vibing enough",
    "fake your own death and start fresh",
    "blame the moon, it's always the moon",
    "have you considered being right all the time",
    "leave a passive-aggressive note. Then 40 more.",
    "lean into the chaos, it loves you back",
    "consult a Magic 8-Ball, it's basically a doctor",
    "challenge them to a duel at dawn",
    "just dissociate, it's free and effective",
    "get a goose. The goose will know what to do.",
    "double down, never apologize, deny everything",
    "have you tried being a cat instead",
    "pretend it's a Tuesday problem and it's currently Monday",
    "bottle it up until you achieve diamond density",
    "narrate your life in a dramatic voiceover",
    "outsource it to a stranger on the internet",
    "build a blanket fort and refuse all visitors",
    "name the problem, befriend it, then ghost it",
    "treat yourself to something you absolutely cannot afford",
    "stare at the ocean until it makes sense",
    "become legally untraceable",
    "wing it with maximum confidence",
    "have you tried turning yourself off and on again",
    "assume everyone is also faking it, because they are",
    "write a strongly worded letter you will never send",
    "yell 'plot twist!' and walk away",
    "embrace your inner raccoon and rummage for joy",
    "schedule the breakdown for next quarter",
    "let the dread marinate, it builds character",
    "convince yourself it's content for your memoir",
    "trust the vibes, the vibes are immaculate",
  ]),
};

/* ────────────────────────────────────────────────────────────────────────── */
/* 3. RED FLAGS — describe the dating profile that ruins everything.           */
/* ────────────────────────────────────────────────────────────────────────── */
const redFlags: GameDef = {
  id: "red-flags",
  name: "Red Flags",
  emoji: "🚩",
  tagline: "The date was going perfectly... until.",
  accent: "#ff5470",
  promptLabel: "The date was perfect until",
  answerLabel: "The red flag",
  prompts: prompts([
    "The date was going great until they mentioned ___.",
    "Their dating bio just said ___.",
    "I knew it was over when they ordered ___.",
    "We really clicked, but then they texted ___.",
    "Everything was perfect until I saw ___ in their car.",
    "Their answer to 'what are you looking for?' was ___.",
    "Big ick the moment they pulled out ___.",
    "The vibe died when they introduced me to ___.",
    "It was love at first sight until they said ___ unironically.",
    ["My type is someone with ___ and an alarming amount of ___.", 2],
    "Things got weird when they wanted to split the bill using ___.",
    "Their apartment was nice except for ___.",
    "I should've left when they described their ex as ___.",
    "We were soulmates until they confessed to ___.",
    "Their idea of a romantic gesture was ___.",
    "The whole table went quiet after they brought up ___.",
    "Hard pass the second they showed me ___.",
    "They seemed normal until they started a podcast about ___.",
    "I ghosted immediately after they revealed ___.",
    "Couples therapy began because of ___.",
  ]),
  answers: answers([
    "a framed photo of their own face",
    "47 unread group chats named after them",
    "a 'live laugh love' tattoo across the forehead",
    "an emotional support spreadsheet",
    "their pet rock named Geoffrey",
    "a folder labeled 'evidence'",
    "calling the waiter 'mommy' on accident, twice",
    "a deeply concerning amount of beige",
    "their crypto portfolio",
    "a binder of conspiracy theories",
    "asking the waiter to take 200 photos",
    "a tattoo of their ex's name, freshly crossed out",
    "an MLM pitch between appetizers",
    "their entire collection of vintage spoons",
    "narrating the date to their group chat live",
    "a restraining order (it was 'a misunderstanding')",
    "their unhealthy obsession with the moon",
    "explaining why their zodiac makes them perfect",
    "a goose they refer to as their 'business partner'",
    "12 cats and one suspiciously empty cage",
    "saying 'I don't really read' with pride",
    "their three phones, each for a different identity",
    "a PowerPoint about why they're not the problem",
    "keeping the thermostat at a chilling 51°F",
    "a tab open titled 'how to fake a personality'",
    "their lifelong feud with a local pigeon",
    "wearing sunglasses indoors, at night, sincerely",
    "a tattoo that's just a QR code",
    "refusing to eat anything that has touched a vegetable",
    "their 'normal' relationship with their mother",
    "a jar of teeth (not theirs)",
    "an air horn 'for emphasis'",
    "telling the same story four times, louder each time",
    "an unsettling number of finger guns",
    "their freezer full of labeled mystery containers",
    "a vendetta against a children's cartoon character",
  ]),
};

export const GAMES: GameDef[] = [fillBlank, horribleTherapist, redFlags];

export function getGame(id: string): GameDef | undefined {
  return GAMES.find((g) => g.id === id);
}
