import type { GameDef, PromptCard, AnswerCard } from "./types";

function prompts(arr: Array<string | [string, number]>): PromptCard[] {
  return arr.map((item, i) => {
    if (Array.isArray(item)) {
      return { id: `p${i}`, text: item[0], pick: item[1] };
    }
    return { id: `p${i}`, text: item };
  });
}

function answers(arr: string[]): AnswerCard[] {
  return arr.map((text, i) => ({ id: `a${i}`, text }));
}

/* ────────────────────────────────────────────────────────────────────────── */
/* 1. FILL IN THE BLANK — a Cards Against Humanity-style absurd party game.     */
/* ────────────────────────────────────────────────────────────────────────── */
const fillBlank: GameDef = {
  id: "fill-blank",
  name: "Fill In The Blank",
  emoji: "🃏",
  tagline: "Complete the sentence. Regret nothing.",
  accent: "#f5c518",
  promptLabel: "The prompt",
  answerLabel: "Your hand",
  prompts: prompts([
    "My therapist says my biggest red flag is ___.",
    "The secret ingredient in grandma's famous recipe is ___.",
    "I got fired for bringing ___ to the company picnic.",
    "Nothing ruins a first date faster than ___.",
    "The new Olympic sport that nobody asked for: ___.",
    "What's keeping me up at 3 a.m.? ___.",
    "The motivational poster in hell just says ___.",
    "I'd be a millionaire if I had a dollar for every ___.",
    "Welcome to my TED Talk on ___.",
    "The real reason the dinosaurs went extinct: ___.",
    ["My autobiography is titled ___, and the sequel is ___.", 2],
    "Studies show that 9 out of 10 doctors recommend ___.",
    "The group chat went silent after someone sent ___.",
    "My spirit animal is just ___ in a tiny hat.",
    "The worst possible thing to whisper during a hug: ___.",
    "Customer service can't help you with ___.",
    "I knew the wedding was doomed when I saw ___.",
    "Step one of my morning routine is ___.",
    ["A balanced breakfast includes ___ and a healthy serving of ___.", 2],
    "The haunted house was scary until we found ___ in the basement.",
    "My final words will probably be about ___.",
    "The app store rejected my app because of ___.",
    "The fortune cookie ominously read ___.",
    "My houseplant died from ___.",
    ["The recipe calls for two cups of ___ and a pinch of ___.", 2],
    "Breaking news: local man arrested for ___.",
    "The wifi password is just ___.",
    "I can't go back to that restaurant because of ___.",
  ]),
  answers: answers([
    "aggressively making eye contact",
    "a possum playing dead for attention",
    "aggressive small talk",
    "the office printer that smells fear",
    "an unsolicited drum solo",
    "filing taxes for my imaginary friend",
    "a haunted vending machine",
    "emotional damage, sponsored by my ex",
    "committing to the bit forever",
    "a duck-sized horse (or a horse-sized duck)",
    "a single, perfect chicken nugget",
    "emotional support raccoons",
    "explaining the plot of Inception, uninvited",
    "a suspiciously confident toddler",
    "my browser history",
    "screaming into a decorative pillow",
    "the audacity",
    "a PowerPoint with 94 slides",
    "running away from my responsibilities",
    "an unpaid internship",
    "haunted Tupperware",
    "the slow descent into madness",
    "interpretive dance",
    "a goose with a vendetta",
    "passive-aggressive sticky notes",
    "crying in the cereal aisle",
    "a motivational speaker nobody hired",
    "questionable life choices",
    "a raccoon wearing a tuxedo",
    "existential dread, but make it fashion",
    "gluten",
    "a Roomba seeking revenge",
    "my unread emails",
    "selling feet pics to the mafia",
    "a lukewarm cup of disappointment",
    "the ghost of my New Year's resolutions",
    "an inflatable T-Rex costume",
    "way too much confidence and zero plan",
    "a clown with a law degree",
    "spontaneous combustion",
    "my one (1) personality trait",
    "a deeply cursed Roomba",
    "the void, but it has wifi",
    "a pigeon that knows what it did",
    "tax fraud, allegedly",
  ]),
};

/* ────────────────────────────────────────────────────────────────────────── */
/* 2. HORRIBLE THERAPIST — give the worst possible advice to real problems.    */
/* ────────────────────────────────────────────────────────────────────────── */
const horribleTherapist: GameDef = {
  id: "horrible-therapist",
  name: "Horrible Therapist",
  emoji: "🛋️",
  tagline: "A patient needs help. Give them the worst advice imaginable.",
  accent: "#7c5cff",
  promptLabel: "The patient says",
  answerLabel: "Your professional advice",
  prompts: prompts([
    "\"I think my roommate is stealing my food.\" Doctor, what should I do?",
    "\"I'm terrified of public speaking.\" How do I get over it?",
    "\"My partner says I never listen.\" How can I improve?",
    "\"I keep procrastinating on everything.\" Help me fix this.",
    "\"I'm having trouble sleeping at night.\" Any advice?",
    "\"My boss takes credit for all my work.\" What do I do?",
    "\"I get anxious in large crowds.\" How should I cope?",
    "\"I can't stop comparing myself to others.\" What now?",
    "\"My kids won't stop fighting.\" Doctor, please.",
    "\"I'm scared of commitment.\" How do I move forward?",
    "\"I have a big presentation tomorrow.\" Calm me down.",
    "\"I think I'm burnt out at work.\" What's the cure?",
    "\"My neighbor plays loud music at 2 a.m.\" Help.",
    "\"I feel like nobody understands me.\" What should I try?",
    "\"I'm nervous about meeting my in-laws.\" Tips?",
    "\"I keep having the same nightmare.\" What does it mean?",
    "\"I spent my whole paycheck already.\" How do I budget?",
    "\"I'm afraid of growing old.\" How do I make peace with it?",
    "\"My friend never texts back.\" Should I be worried?",
    "\"I can't focus when I work from home.\" Suggestions?",
    "\"I argue with strangers online all day.\" Help me stop.",
    "\"I'm always running late.\" How do I fix my timing?",
    "\"I can't say no to anyone.\" What do I do?",
    "\"I'm jealous of my best friend's success.\" Advice?",
    "\"I keep losing my keys.\" Any tips?",
    "\"I overthink every text I send.\" Help.",
  ]),
  answers: answers([
    "have you tried screaming about it instead",
    "incorporate as a small business and write it off",
    "respond only with the thumbs-up emoji, forever",
    "achieve inner peace by escalating immediately",
    "let a raccoon make your decisions for a week",
    "speak only in fortune-cookie wisdom from now on",
    "delegate your feelings to a houseplant",
    "rebrand the problem as a 'premium feature'",
    "consult the ancient wisdom of a wall calendar",
    "simply become the villain",
    "respond exclusively in interpretive dance",
    "move to the woods and adopt a crow",
    "set everything you own on fire (metaphorically)(or not)",
    "manifest it harder, you're just not vibing enough",
    "fake your own death and start fresh",
    "blame the moon, it's always the moon",
    "have you considered being right all the time",
    "leave a passive-aggressive note. Then 40 more.",
    "lean into the chaos, it loves you back",
    "consult a Magic 8-Ball, it's basically a doctor",
    "challenge them to a duel at dawn",
    "just dissociate, it's free and effective",
    "get a goose. The goose will know what to do.",
    "double down, never apologize, deny everything",
    "have you tried being a cat instead",
    "pretend it's a Tuesday problem and it's currently Monday",
    "bottle it up until you achieve diamond density",
    "narrate your life in a dramatic voiceover",
    "outsource it to a stranger on the internet",
    "build a blanket fort and refuse all visitors",
    "name the problem, befriend it, then ghost it",
    "treat yourself to something you absolutely cannot afford",
    "stare at the ocean until it makes sense",
    "become legally untraceable",
    "wing it with maximum confidence",
    "have you tried turning yourself off and on again",
    "assume everyone is also faking it, because they are",
    "write a strongly worded letter you will never send",
    "yell 'plot twist!' and walk away",
    "embrace your inner raccoon and rummage for joy",
    "schedule the breakdown for next quarter",
    "let the dread marinate, it builds character",
    "convince yourself it's content for your memoir",
    "trust the vibes, the vibes are immaculate",
  ]),
};

/* ────────────────────────────────────────────────────────────────────────── */
/* 3. RED FLAGS — describe the dating profile that ruins everything.           */
/* ────────────────────────────────────────────────────────────────────────── */
const redFlags: GameDef = {
  id: "red-flags",
  name: "Red Flags",
  emoji: "🚩",
  tagline: "The date was going perfectly... until.",
  accent: "#ff5470",
  promptLabel: "The date was perfect until",
  answerLabel: "The red flag",
  prompts: prompts([
    "The date was going great until they mentioned ___.",
    "Their dating bio just said ___.",
    "I knew it was over when they ordered ___.",
    "We really clicked, but then they texted ___.",
    "Everything was perfect until I saw ___ in their car.",
    "Their answer to 'what are you looking for?' was ___.",
    "Big ick the moment they pulled out ___.",
    "The vibe died when they introduced me to ___.",
    "It was love at first sight until they said ___ unironically.",
    ["My type is someone with ___ and an alarming amount of ___.", 2],
    "Things got weird when they wanted to split the bill using ___.",
    "Their apartment was nice except for ___.",
    "I should've left when they described their ex as ___.",
    "We were soulmates until they confessed to ___.",
    "Their idea of a romantic gesture was ___.",
    "The whole table went quiet after they brought up ___.",
    "Hard pass the second they showed me ___.",
    "They seemed normal until they started a podcast about ___.",
    "I ghosted immediately after they revealed ___.",
    "Couples therapy began because of ___.",
    "Their car air freshener was shaped like ___.",
    "Their idea of a fun weekend was ___.",
    "They proudly told me their nickname was ___.",
    "The first gift they ever gave me was ___.",
    "They paused the movie to explain ___.",
  ]),
  answers: answers([
    "a framed photo of their own face",
    "a laminated list of their ex's flaws",
    "their fan-fiction starring themselves",
    "a podcast mic permanently in the passenger seat",
    "a 'World's Okayest' mug collection",
    "an emotional support sourdough starter named Greg",
    "their unblinking commitment to pyramid schemes",
    "a binder titled 'Future Wedding (yours)'",
    "a deeply personal vendetta against seagulls",
    "a tattoo of the WiFi symbol",
    "47 unread group chats named after them",
    "a 'live laugh love' tattoo across the forehead",
    "an emotional support spreadsheet",
    "their pet rock named Geoffrey",
    "a folder labeled 'evidence'",
    "calling the waiter 'mommy' on accident, twice",
    "a deeply concerning amount of beige",
    "their crypto portfolio",
    "a binder of conspiracy theories",
    "asking the waiter to take 200 photos",
    "a tattoo of their ex's name, freshly crossed out",
    "an MLM pitch between appetizers",
    "their entire collection of vintage spoons",
    "narrating the date to their group chat live",
    "a restraining order (it was 'a misunderstanding')",
    "their unhealthy obsession with the moon",
    "explaining why their zodiac makes them perfect",
    "a goose they refer to as their 'business partner'",
    "12 cats and one suspiciously empty cage",
    "saying 'I don't really read' with pride",
    "their three phones, each for a different identity",
    "a PowerPoint about why they're not the problem",
    "keeping the thermostat at a chilling 51°F",
    "a tab open titled 'how to fake a personality'",
    "their lifelong feud with a local pigeon",
    "wearing sunglasses indoors, at night, sincerely",
    "a tattoo that's just a QR code",
    "refusing to eat anything that has touched a vegetable",
    "their 'normal' relationship with their mother",
    "a jar of teeth (not theirs)",
    "an air horn 'for emphasis'",
    "telling the same story four times, louder each time",
    "an unsettling number of finger guns",
    "their freezer full of labeled mystery containers",
    "a vendetta against a children's cartoon character",
  ]),
};

/* ────────────────────────────────────────────────────────────────────────── */
/* 4. UNICORN CHAOS — magical, glittery, faintly unhinged.                     */
/* ────────────────────────────────────────────────────────────────────────── */
const unicornChaos: GameDef = {
  id: "unicorn-chaos",
  name: "Unicorn Chaos",
  emoji: "🦄",
  tagline: "Friendship, sparkles, and mild chaos magic.",
  accent: "#ff8fd4",
  promptLabel: "The prophecy reads",
  answerLabel: "Your magic",
  prompts: prompts([
    "The unicorn kingdom fell the day someone introduced ___.",
    "My horn grants the magical power of ___.",
    "We don't talk about what happened at the Glitter Festival and ___.",
    "The rainbow bridge is closed today due to ___.",
    "A true unicorn never leaves home without ___.",
    "The dark wizard's only weakness is ___.",
    "I traded my entire cloud castle for ___.",
    "The sacred fountain now dispenses ___ instead of wishes.",
    "Every legend agrees: the chosen one will arrive riding ___.",
    "The fairy council banished me for ___.",
    ["My spell backfired and turned the prince into ___ and ___.", 2],
    "The enchanted forest smells suspiciously like ___.",
    "I knew the potion was cursed when it started ___.",
    "Behold, the most powerful artifact in the realm: ___.",
    "The dragon agreed to a truce in exchange for ___.",
    "Our kingdom's national anthem is just three hours of ___.",
    "The wizard academy expelled me for summoning ___.",
    "True love's kiss was ruined by ___.",
    "The royal banquet was ruined by ___.",
    "My familiar is a ___ with serious anger issues.",
    "I opened a portal, but it only leads to ___.",
    "The kingdom's official currency is now ___.",
    "The wise old owl's only advice was ___.",
  ]),
  answers: answers([
    "a horn that only plays kazoo",
    "a unicorn influencer chasing brand deals",
    "a spell that just makes everything slightly sticky",
    "an enchanted sword that only cuts cake",
    "a dragon hoarding novelty socks",
    "a rainbow with crippling self-doubt",
    "weaponized jazz hands",
    "a goblin who only speaks in puns",
    "the legendary +1 Spoon of Mild Inconvenience",
    "a fairy ring that turned out to be an HOA",
    "weaponized friendship",
    "an alarming amount of glitter",
    "a rainbow that leads nowhere",
    "the power to summon mildly inconvenient weather",
    "a cloud that's secretly judging you",
    "a sparkle so bright it voids the warranty",
    "an emotionally unavailable dragon",
    "a fairy with commitment issues",
    "biting the chosen one (gently)",
    "a unicorn who refuses to use its indoor voice",
    "glitter that will never, ever come out",
    "a prophecy written in crayon",
    "a magical pony with a gambling problem",
    "turning everyone into smaller ponies",
    "a wizard hat two sizes too small",
    "a potion that just makes you slightly damp",
    "an enchanted snack that talks back",
    "friendship, but legally binding",
    "a rainbow with a restraining order",
    "the forbidden third horn",
    "a spell that only works on Tuesdays",
    "a dragon who's 'not mad, just disappointed'",
    "a tiny crown for a very large ego",
    "interpretive prancing",
    "a cursed cupcake",
    "the power of aggressive whimsy",
    "a moonbeam that owes me money",
    "galloping away from my problems",
    "a sparkly void where my homework used to be",
    "a fairy godmother with a 2-star rating",
    "screaming, but make it magical",
  ]),
};

/* ────────────────────────────────────────────────────────────────────────── */
/* 5. CAT-ASTROPHE — chaotic feline energy.                                    */
/* ────────────────────────────────────────────────────────────────────────── */
const catAstrophe: GameDef = {
  id: "cat-astrophe",
  name: "Cat-astrophe",
  emoji: "🐱",
  tagline: "Knock it off the table. All of it.",
  accent: "#ffb454",
  promptLabel: "The cat demands",
  answerLabel: "Your offering",
  prompts: prompts([
    "At 3 a.m. my cat needs me to know about ___.",
    "I was late for work because of ___.",
    "The vet bill was so high because of ___.",
    "My cat knocked ___ off the table, maintaining eye contact.",
    "The reason there's a dead thing on my pillow is ___.",
    "My cat's one-star review of me mentions ___.",
    "I can't use my laptop right now because of ___.",
    "The litter box situation has escalated to ___.",
    "My cat is plotting ___, I just know it.",
    "Forget the expensive toy — my cat only wants ___.",
    ["The new cat tower comes with ___ and a free ___.", 2],
    "The mysterious 2 a.m. zoomies were caused by ___.",
    "My cat will tolerate me only if I provide ___.",
    "I found ___ hidden under the couch again.",
    "The cat café was shut down after an incident involving ___.",
    "My cat stares at the wall because of ___.",
    "The only thing my cat fears is ___.",
    "I've been replaced in my cat's heart by ___.",
    "My cat proudly brought home ___ as a trophy.",
    "My cat's secret online username is ___.",
    "The pet camera caught my cat ___.",
    "My cat will only eat from a bowl shaped like ___.",
    "I woke up to find ___ carefully placed in my shoe.",
  ]),
  answers: answers([
    "a single crinkly receipt",
    "a single sock I never owned",
    "the neighbor's entire welcome mat",
    "a 3 a.m. parkour incident",
    "judging my life choices from the windowsill",
    "an heirloom hairball collection",
    "a live bug it refuses to actually catch",
    "a feather it found and now guards with its life",
    "a war crime against the toilet paper roll",
    "knocking the houseplant over, maintaining eye contact",
    "the empty box the bed came in",
    "knocking over exactly one glass of water",
    "a 4 a.m. opera performance",
    "the red dot that got away",
    "sitting directly on the keyboard",
    "a hairball of impressive structural integrity",
    "an unprovoked ankle ambush",
    "the betrayal of a closed door",
    "a feather on a string (the betrayal)",
    "judgmental loaf mode",
    "a half-eaten gift left in my shoe",
    "the vacuum cleaner's reign of terror",
    "a cardboard box worth more than my rent",
    "screaming at a bird through glass",
    "a sunbeam that moved two inches",
    "knocking my phone into the toilet",
    "demanding food it will not eat",
    "a 6 a.m. wake-up via face-walk",
    "the forbidden houseplant",
    "a toe under the blanket",
    "an unblinking 3 a.m. stare",
    "the crinkliest bag in the house",
    "a sock that is now legally the cat's",
    "zooming across the apartment for no reason",
    "sitting on the one document I need",
    "a strategically placed hairball",
    "the laser pointer industrial complex",
    "a tail with its own agenda",
    "ignoring me with great enthusiasm",
    "the warm laundry, fresh from the dryer",
    "a tiny mouse toy soaked in drool",
  ]),
};

export const GAMES: GameDef[] = [fillBlank, horribleTherapist, redFlags, unicornChaos, catAstrophe];

export function getGame(id: string): GameDef | undefined {
  return GAMES.find((g) => g.id === id);
}
